### ISSUE TITLE
rimraf *.marko.js potentially unnecessary.

### ISSUE THREAD

**Issue by DylanPiercey** [gladejs/gladejs#2]
I saw the recommended `clean` command is primarily to remove `*.marko.js` files. Since I don't think you actually are relying on these files being written to disc it might be better to leverage the `writeToDisk: false` compiler option.

Basically just replace https://github.com/gladejs/gladejs/blob/0dbcb8b4cec80590a0d440ab60fd7c58518f5a0c/rollup-plugin.js#L4 with

```js
import { install } from "marko/node-require"

install({ compilerOptions: { writeToDisk: false } });
```

**Comment by AurelienStebe** [comment]
Absolutely, those files were useful at first to see what was going on, but now they are kind of "in the way".

This will be implemented for the next release, expect a commit to close this ASAP. Thanks.
